# Generated by Django 4.2.5 on 2023-10-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialnetwork", "0003_alter_comment_creation_time_alter_post_creation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="creation_time", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="post", name="creation_time", field=models.DateTimeField(),
        ),
    ]
